import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import '../styles/globals.css';
import ReactQueryClientProvider from './_components/ReactQueryClientProvider';
import { cn } from '@/lib/utils';
import { createServerSupabaseClient } from './utils/supabase/server';
import AuthProvider from './_components/AuthProvider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createServerSupabaseClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <AuthProvider accessToken={session?.access_token}>
          <ReactQueryClientProvider>{children}</ReactQueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
